#!/bin/bash

thinkfan="/etc/thinkfan.conf"
dev=$(find /sys/devices -type f -name "temp*_input"|sed 's/^/hwmon /g')

echo "$dev" > $thinkfan

printf "
tp_fan /proc/acpi/ibm/fan

(1,	60,	65)
(2,	65,	70)
(3,	70,	75)
(4,	75,	80)
(5,	80,	85)
(7,	85,	32767)" >> $thinkfan 

# devconf = device temperature and fan speed configs for ThinkFan, respectively
printf "thinkfan is configured for %d devices.\n" "$(echo \""$dev\""|wc -l)"
