#!/bin/bash 

docker run --rm --name telegram \
    --hostname="$(hostname)" \
    -e DISPLAY=unix"$DISPLAY" \
    -e PULSE_SERVER=unix:"$XDG_RUNTIME_DIR/pulse/native" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v "/home/$(whoami)/.Xauthority:/home/user/.Xauthority" \
    -v "$XDG_RUNTIME_DIR"/pulse:"$XDG_RUNTIME_DIR"/pulse \
    -v /etc/localtime:/etc/localtime:ro \
    -v ~/Downloads/.TelegramDesktop:/home/user/.local/share/TelegramDesktop/ \
    -v ~/Downloads/:/home/user/Downloads/ \
    -v /tmp/:/tmp/ \
    --network=host \
    ghcr.io/xorilog/docker-telegram/telegram &>/dev/null & disown

# -v /home/javad/Downloads/Telegram\ Desktop:/home/user/Downloads/Telegram\ Desktop/ \
