#!/bin/bash
value=$(gsettings get org.gnome.desktop.notifications show-banners)
if [[ $value == 'true' ]]
then
  gsettings set org.gnome.desktop.notifications show-banners false
  gnome-extensions enable hidetopbar@mathieu.bidon.ca
else
  gsettings set org.gnome.desktop.notifications show-banners true
  gnome-extensions disable hidetopbar@mathieu.bidon.ca
fi
