#!/bin/bash

IFS=$'\n'

# Default values
current_directory="$(pwd)"
paths=(".")

clean_latex_temp()
{
    rm -fv -- *.{aux,log,dvi,idx,ilg,ind,toc,out,pyg,tdo,blg,lot,lol,lof}
    rm -fv -- *.{synctex,synctex.gz,synctex\(busy\)}
    rm -fv -- *.{syn,suc,bbl,syc,brf,los,snm,nav,gnuplot,hd,bbl,blg,bcf,run.xml,listing}
    rm -fv -- *~
}

clean_python_temp()
{
    rm -rfv __pycache__
}

# Parse command-line options
while [[ "$#" -gt 0 ]]; do
    case $1 in
        *)
            paths+=("$1")
            shift
            ;;
    esac
done

for ((i=0; i<${#paths[@]}; i++)); do
    echo "Entering Directory ${paths[i]} ..."
    cd "${paths[i]}" || exit
    clean_latex_temp
    clean_python_temp
done

cd "$current_directory" || exit
