#!/bin/bash 

clean_latex_temp()
{
    rm -rifv *.aux *.log *.dvi *.idx *.ilg *.ind *.toc *.out *.pyg *.synctex *.tdo *.blg \
             *.lot *.lol *.lof *.syn *.suc *.bbl *.syc *.brf *.los *.snm *.nav *.gnuplot *.hd\
             *.bbl *.blg *.bcf *.run.xml *.listing *~
}

clean_python_temp()
{
    rm -rifv __pycache__
}

clean_latex_temp
clean_python_temp

if [ -d chapters ];then 
    cd chapters
    clean_latex_temp
    cd ..
fi
