#!/bin/bash
curDir="$(pwd)"

cd ~ || exit
rsync -rltzz --delete --progress  --modify-window=5  -vh --exclude="mactex*" rsync://rsync.dante.ctan.org/CTAN/systems/texlive/tlnet/ "texlive-xz"
# rsync -rltzz --delete --progress  --modify-window=5  -vh --exclude="mactex*" rsync://mirror.asis.sh/CTAN/systems/texlive/tlnet/ "texlive-xz"
# rsync -rltzz --delete --progress  --modify-window=5  -vh --exclude="mactex*" rsync://mirror.bardia.tech/ctan/systems/texlive/tlnet/ "texlive-xz"
cd "$curDir" || exit

